CLASS ycl_op_pos_upload DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    INTERFACES if_oo_adt_classrun .
    CLASS-METHODS LOAD_YOP_T_BANKACC.
    CLASS-METHODS LOAD_YOP_T_BANKFORMAT.
    CLASS-METHODS LOAD_YOP_T_BNKINF.
    CLASS-METHODS LOAD_YOP_T_FIELDCALC.
    CLASS-METHODS LOAD_YOP_T_POSFIELD.
    CLASS-METHODS LOAD_YOP_T_PTYPEMATCH.
    CLASS-METHODS RUN_ALL.