  METHOD run_upload_hesapci.

    DATA lt_data TYPE STANDARD TABLE OF yop_t_posfield .

    lt_data = VALUE #(
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 1 bank_field = 'Zincir No' alv_field = 'ZZCENTER_NUMBER' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 2 bank_field = 'Uye Isyeri No' alv_field = 'WORKPLACE_NO' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 3 bank_field = 'Terminal Id' alv_field = 'TERMINAL_NO' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 4 bank_field = 'Uye Isyeri Adi' alv_field = 'ZZMEMBER_WORKPLC_NAME' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 5 bank_field = 'Islem Tarihi' alv_field = 'TRANSACTION_DATE' date_format = 'DD.MM.YYYY' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 6 bank_field = 'Gunsonutarihi' alv_field = 'ZZEND_OF_DAY_DATE' date_format = 'DD.MM.YYYY' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 7 bank_field = 'Kart No' alv_field = 'CARD_NO' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 8 bank_field = 'Ana Kart Tipi' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 9 bank_field = 'Alt Kart Tipi' alv_field = 'CARD_TYPE' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 10 bank_field = 'Islem Tipi' alv_field = 'PROCESS_TYPE' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 11 bank_field = 'Provizyon No' alv_field = 'PROVISION_APR_CODE' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 12 bank_field = 'Taksit Sira' alv_field = 'INSTALLMENT_ORDER' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 13 bank_field = 'Taksit Sayi' alv_field = 'INSTALLMENT_NUMBER' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 14 bank_field = 'Provizyon Tutari' alv_field = 'GROSS_AMOUNT' date_format = '' time_format = '' amount_format = '0.0,00' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 15 bank_field = 'Komisyon Tutari' alv_field = 'COMMISSION_AMOUNT' date_format = '' time_format = '' amount_format = '0.0,00' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 16 bank_field = 'Eo Kes Tut' alv_field = 'COMMISSION_AMOUNT' date_format = '' time_format = '' amount_format = '0.0,00' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 17 bank_field = 'Net Tutar' alv_field = 'NET_AMOUNT' date_format = '' time_format = '' amount_format = '0.0,00' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 18 bank_field = 'Valortarihi' alv_field = 'VALUE_DATE' date_format = 'DD.MM.YYYY' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 19 bank_field = 'İklcom Chip' alv_field = 'GROSS_AMOUNT' date_format = '' time_format = '' amount_format = '0.0,00' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 20 bank_field = 'Vrcom Chip' alv_field = 'COMMISSION_AMOUNT' date_format = '' time_format = '' amount_format = '0.0,00' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 21 bank_field = 'Kesilen Chip' alv_field = 'COMMISSION_AMOUNT' date_format = '' time_format = '' amount_format = '0.0,00' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 22 bank_field = 'Net Chip' alv_field = 'NET_AMOUNT' date_format = '' time_format = '' amount_format = '0.0,00' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 23 bank_field = 'Chip Para Valor Tarihi' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 24 bank_field = 'Aud Key' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 25 bank_field = 'Mevduat Hesap No' alv_field = 'ZZACCOUNT_NUMBER' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 26 bank_field = 'Uye Isyeri Mbb No' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 27 bank_field = 'Banka Kodu ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 1 bank_field_no = 28 bank_field = 'Uyb Mev Iban No ' alv_field = 'ZZIBAN' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 1 bank_field = 'Şube No' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 2 bank_field = 'Grup No' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 3 bank_field = 'Üye No' alv_field = 'WORKPLACE_NO' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 4 bank_field = 'Üye Adı' alv_field = 'ZZMEMBER_WORKPLC_NAME' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 5 bank_field = 'Store No' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 6 bank_field = 'Kart Tipi' alv_field = 'CARD_TYPE' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 7 bank_field = 'Bloke Tarihi' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 8 bank_field = 'Çözülme Tarihi' alv_field = 'TRANSACTION_DATE' date_format = 'DD/MM/YYYY' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 9 bank_field = 'Bekleyen Borc Tutarı' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 10 bank_field = 'Bekleyen Alacak Tutarı' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 11 bank_field = 'Çözülen Borç tutarı' alv_field = 'INTERRUPT_AMOUNT' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 12 bank_field = 'Çözülen Alacak Tutarı' alv_field = 'GROSS_AMOUNT' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 13 bank_field = 'Bekleyen Puan' alv_field = '' date_format = 'DD/MM/YYYY' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 14 bank_field = 'Çözülen Puan' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 15 bank_field = 'Bekleyen Net' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 16 bank_field = 'Çözülen Net' alv_field = 'NET_AMOUNT' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 17 bank_field = 'Servis Açıklama' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 18 bank_field = 'Servis Kodu' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 19 bank_field = 'Komisyon Oranı' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 20 bank_field = 'Bloke Suresi' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 21 bank_field = 'Bloke Hesap No' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 22 bank_field = 'Vadesiz Hesap No' alv_field = '' date_format = '' time_format = 'HH:MM:SS' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 23 bank_field = 'Hesaba Geçiş Tarihi' alv_field = 'VALUE_DATE' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 24 bank_field = 'Vadesiz IBAN' alv_field = 'ZZIBAN' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 25 bank_field = 'Para Birimi' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 26 bank_field = 'Bekleyen Taksitli İşlem Ücreti' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 27 bank_field = 'Bekleyen İndirim' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 28 bank_field = 'Çözülen Taksitli İşlem Ücreti' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 29 bank_field = 'Çözülen İndirim' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 30 bank_field = 'Bekleyen Borç Tutarı (Döviz)' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 31 bank_field = 'Bekleyen Alacak Tutarı (Döviz)' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 32 bank_field = 'Bekleyen Puan (Döviz)' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 33 bank_field = 'Bekleyen Taksitli İşlem Ücreti (Döviz)' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 34 bank_field = 'Çözülmüş Borç Tutarı (Döviz)' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 35 bank_field = 'Çözülmüş Alacak Tutarı (Döviz)' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 36 bank_field = 'Çözülmüş Puan (Döviz)' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 37 bank_field = 'Çözülmüş Taksitli İşlem Ücreti (Döviz)' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 38 bank_field = 'Müşteri No' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 39 bank_field = 'Kur' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 40 bank_field = 'Kampanyasız Komisyon' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 41 bank_field = 'Kampanyasız Bloke Valör' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 42 bank_field = 'BSMV Tutar' alv_field = 'COMMISSION_AMOUNT' date_format = '' time_format = '' amount_format = '0.00' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 43 bank_field = 'Üst Bayi Üye No' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 2 bank_field_no = 44 bank_field = '0' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 1 bank_field = 'UYEISY  ' alv_field = 'WORKPLACE_NO' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 2 bank_field = 'TRMNO  ' alv_field = 'TERMINAL_NO' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 3 bank_field = 'TKSTID  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 4 bank_field = 'ISLTAR  ' alv_field = 'TRANSACTION_DATE' date_format = 'DD.MM.YYYY' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 5 bank_field = 'KRTNO  ' alv_field = 'CARD_NO' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 6 bank_field = 'KART_TIP  ' alv_field = 'CARD_TYPE' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 7 bank_field = 'ORJTUT  ' alv_field = 'GROSS_AMOUNT' date_format = '' time_format = '' amount_format = '0' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 8 bank_field = 'BLOKCOZTAR  ' alv_field = 'VALUE_DATE' date_format = 'DD/MM/YYYY' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 9 bank_field = 'NETODMTUT  ' alv_field = 'NET_AMOUNT' date_format = '' time_format = '' amount_format = '0' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 10 bank_field = 'KMSYN  ' alv_field = 'COMMISSION_AMOUNT' date_format = '' time_format = '' amount_format = '0' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 11 bank_field = 'KPAY  ' alv_field = '' date_format = '' time_format = '' amount_format = '0' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 12 bank_field = 'ERKODMTUT  ' alv_field = '' date_format = '' time_format = '' amount_format = '0' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 13 bank_field = 'ERKBLKKOM  ' alv_field = '' date_format = '' time_format = '' amount_format = '0' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 14 bank_field = 'TKSTADEDI  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 15 bank_field = 'TKSTSIRASI  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 16 bank_field = 'SUBE  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 17 bank_field = 'TIP  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 18 bank_field = 'HSP  ' alv_field = 'ZZACCOUNT_NUMBER' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 19 bank_field = 'ISLTIP  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 20 bank_field = 'CIF_CUSTNO  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 21 bank_field = 'PRVZTAR  ' alv_field = '' date_format = 'DD/MM/YYYY' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 22 bank_field = 'IADEUYEISY  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 23 bank_field = 'AUTH_NBR  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 24 bank_field = 'REFERANS_NO  ' alv_field = 'ZZCENTER_NUMBER' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 25 bank_field = 'DETAY_TAKSIT_TOPLAM_TUTAR_CCY  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 26 bank_field = 'DETAY_TAKSIT_TOPLAM_TUTAR_ORJ  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 27 bank_field = 'SANAL_POS_ID  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 28 bank_field = 'YENI_UYEISY  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 29 bank_field = 'TABELA_UNVANI  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 3 bank_field_no = 30 bank_field = 'ISLSAATI' alv_field = '' date_format = '' time_format = 'HH:MM:SS' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 1 bank_field = 'Mono  ' alv_field = 'PROVISION_APR_CODE' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 2 bank_field = 'Ticari Ünvan  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 3 bank_field = 'Vergi No  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 4 bank_field = 'Zincir No  ' alv_field = 'ZZCENTER_NUMBER' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 5 bank_field = 'İşyeri No  ' alv_field = 'WORKPLACE_NO' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 6 bank_field = 'İşyeri Adı  ' alv_field = 'ZZMEMBER_WORKPLC_NAME' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 7 bank_field = 'MCC  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 8 bank_field = 'Terminal Numarası  ' alv_field = 'TERMINAL_NO' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 9 bank_field = 'İşlem Tarihi  ' alv_field = 'TRANSACTION_DATE' date_format = 'DD.MM.YYYY' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 10 bank_field = 'İşlem Saati  ' alv_field = 'ZZTRANSACTION_TIME' date_format = '' time_format = 'HHMMSS' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 11 bank_field = 'Hesaba Geçiş Tarihi Valor  ' alv_field = 'VALUE_DATE' date_format = 'DD.MM.YYYY' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 12 bank_field = 'Taksit Sayısı  ' alv_field = 'INSTALLMENT_NUMBER' date_format = '' time_format = '' amount_format = '0' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 13 bank_field = 'Taksit No  ' alv_field = 'INSTALLMENT_ORDER' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 14 bank_field = 'Kart No  ' alv_field = 'CARD_NO' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 15 bank_field = 'Kart Tipi  ' alv_field = 'CARD_TYPE' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 16 bank_field = 'Temassız Flag  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 17 bank_field = 'Offline Flag  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 18 bank_field = 'Servis Kodu  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 19 bank_field = 'İşlem Tipi  ' alv_field = 'PROCESS_TYPE' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 20 bank_field = 'İşlem Alt Kodu  ' alv_field = 'PROVISION_APR_CODE' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 21 bank_field = 'İşlem Adı  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 22 bank_field = 'Provizyon Numarası  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 23 bank_field = 'Brüt Tutar  ' alv_field = 'GROSS_AMOUNT' date_format = '' time_format = '' amount_format = '0' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 24 bank_field = 'Komisyon Oranı  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 25 bank_field = 'Komisyon Tutar  ' alv_field = 'COMMISSION_AMOUNT' date_format = '' time_format = '' amount_format = '0' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 26 bank_field = 'Marka Servis Komisyon Oranı  ' alv_field = '' date_format = '' time_format = '' amount_format = '0' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 27 bank_field = 'Marka Servis Komisyon Tutar  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 28 bank_field = 'IKP Oranı  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 29 bank_field = 'IKP Tutar  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 30 bank_field = 'Net Tutar  ' alv_field = 'NET_AMOUNT' date_format = '' time_format = '' amount_format = '0' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 31 bank_field = 'Para Birimi  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 32 bank_field = 'Sipariş No  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 33 bank_field = 'Bloke Süresi  ' alv_field = 'ZZEND_OF_DAY_DATE' date_format = 'DD/MM/YYYY' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 34 bank_field = 'Bloke Tipi  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 35 bank_field = 'Bloke Hesap No  ' alv_field = 'CARD_TYPE' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 36 bank_field = 'Vadesiz Hesap No  ' alv_field = 'ZZACCOUNT_NUMBER' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 37 bank_field = 'Şube Kodu  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 38 bank_field = 'Şube Adı  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 39 bank_field = 'Günsonu Tarihi  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 40 bank_field = 'İşlem Kodu  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 4 bank_field_no = 41 bank_field = 'RRN' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 1 bank_field = 'Gerçekleşen İşlemler' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 2 bank_field = 'Banka Vergi Sicil No' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 3 bank_field = 'Banka Vergi Dairesi' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 4 bank_field = 'Merkez No' alv_field = 'ZZCENTER_NUMBER' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 5 bank_field = 'İşyeri No' alv_field = 'WORKPLACE_NO' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 6 bank_field = 'Ticari Unvan' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 7 bank_field = 'İşletme Adı' alv_field = 'ZZMEMBER_WORKPLC_NAME' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 8 bank_field = 'Bölüm Numarası' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 9 bank_field = 'Bölüm Adı' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 10 bank_field = 'Cari Hesap' alv_field = 'ZZACCOUNT_NUMBER' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 11 bank_field = 'VKN/TCKN' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 12 bank_field = 'İşlem Tarihi' alv_field = 'TRANSACTION_DATE' date_format = 'DD.MM.YYYY' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 13 bank_field = 'İşlem Zamanı' alv_field = 'ZZTRANSACTION_TIME' date_format = '' time_format = 'HH:MM:SS' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 14 bank_field = 'İşlem Türü' alv_field = 'ZZDESCRIPTION' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 15 bank_field = 'İşlem Tipi' alv_field = 'PROCESS_TYPE' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 16 bank_field = 'İşlem Tutarı' alv_field = 'GROSS_AMOUNT' date_format = '' time_format = '' amount_format = '0.0,00' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 17 bank_field = 'Taksit Tarihi' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 18 bank_field = 'Taksit Sayısı' alv_field = 'INSTALLMENT_NUMBER' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 19 bank_field = 'Taksit No' alv_field = 'INSTALLMENT_ORDER' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 20 bank_field = 'Taksit Tutarı' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 21 bank_field = 'Gün Sonu Tarihi' alv_field = 'ZZEND_OF_DAY_DATE' date_format = 'DD.MM.YYYY' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 22 bank_field = 'Hesaba Geçiş Tarihi' alv_field = 'VALUE_DATE' date_format = 'DD.MM.YYYY' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 23 bank_field = 'POS No' alv_field = 'TERMINAL_NO' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 24 bank_field = 'POS İşlem No' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 25 bank_field = 'Onay Kodu' alv_field = 'PROVISION_APR_CODE' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 26 bank_field = 'Kart No' alv_field = 'CARD_NO' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 27 bank_field = 'İşyeri Ücreti Pşn/Tkst(Oran)' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 28 bank_field = 'İşyeri Ücreti Pşn/Tkst(Tutar)' alv_field = 'INTERRUPT_AMOUNT' date_format = '' time_format = '' amount_format = '0.0,00' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 29 bank_field = 'İşyeri Ücreti Pşn/Tkst(Maximum' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 30 bank_field = 'İşyeri Ücreti Pşn/Tkst(Maximum' alv_field = 'COMMISSION_AMOUNT' date_format = '' time_format = '' amount_format = '0.0,00' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 31 bank_field = 'İşyeri Puan Katkı Oranı' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 32 bank_field = 'İşyeri Puan Katkı Tutarı' alv_field = 'COMMISSION_AMOUNT' date_format = '' time_format = '' amount_format = '0.0,00' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 33 bank_field = 'Üye İşyeri Ücreti Taksit (Oran' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 34 bank_field = 'Üye İşyeri Ücreti Taksit (Tuta' alv_field = 'INTERRUPT_AMOUNT' date_format = '' time_format = '' amount_format = '0.0,00' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 35 bank_field = 'Merkez Puan Katkı Oranı' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 36 bank_field = 'Merkez Puan Katkı Tutarı' alv_field = 'INTERRUPT_AMOUNT' date_format = '' time_format = '' amount_format = '0.0,00' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 37 bank_field = 'Merkez Ücreti Taksit (Oran)' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 38 bank_field = 'Merkez Ücreti Taksit (Tutar)' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 39 bank_field = 'Merkez Ücreti Pşn/Tkst(Maximum' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 40 bank_field = 'Merkez Ücreti Pşn/Tkst(Maximum' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 41 bank_field = 'Para Birimi' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 42 bank_field = 'Net Tutar' alv_field = 'NET_AMOUNT' date_format = '' time_format = '' amount_format = '0.0,00' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 43 bank_field = 'Üye İşyeri Bilgisi' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 44 bank_field = 'Recurring ID' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 45 bank_field = 'Recurring Sıra No' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 5 bank_field_no = 46 bank_field = 'Brand' alv_field = 'CARD_TYPE' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 1 bank_field = 'MUTA NO  ' alv_field = 'ZZCENTER_NUMBER' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 2 bank_field = 'TİCARİ UNVAN  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 3 bank_field = 'VERGİ NO  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 4 bank_field = 'ÜYE NO  ' alv_field = 'WORKPLACE_NO' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 5 bank_field = 'ÜYE ADI  ' alv_field = 'ZZMEMBER_WORKPLC_NAME' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 6 bank_field = 'TERM_NO  ' alv_field = 'TERMINAL_NO' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 7 bank_field = 'ISLEM_TARİHİ  ' alv_field = 'TRANSACTION_DATE' date_format = 'DD/MM/YYYY' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 8 bank_field = 'İŞLEM SAATİ  ' alv_field = 'ZZTRANSACTION_TIME' date_format = '' time_format = 'HHMMSS' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 9 bank_field = 'VALOR_TARİHİ  ' alv_field = 'VALUE_DATE' date_format = 'DD/MM/YYYY' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 10 bank_field = 'TAKSİT SAYISI  ' alv_field = 'INSTALLMENT_ORDER' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 11 bank_field = 'TOPLAM TAKSİT  ' alv_field = 'INSTALLMENT_NUMBER' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 12 bank_field = 'KART_NO  ' alv_field = 'CARD_TYPE' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 13 bank_field = 'KART_TİPİ  ' alv_field = 'CARD_TYPE' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 14 bank_field = 'URUN_TİPİ  ' alv_field = 'PROCESS_TYPE' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 15 bank_field = 'ONLINE_FLAG  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 16 bank_field = 'SERVIS_KODU  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 17 bank_field = 'ISLEM_TİPİ  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 18 bank_field = 'PROV_NO  ' alv_field = 'PROVISION_APR_CODE' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 19 bank_field = 'BRÜT_TUTAR  ' alv_field = 'GROSS_AMOUNT' date_format = '' time_format = '' amount_format = '0.00,00' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 20 bank_field = 'KOMİSYON_ORANI  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 21 bank_field = 'KOMİSYON_TUTAR  ' alv_field = 'COMMISSION_AMOUNT' date_format = '' time_format = '' amount_format = '0.00,00' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 22 bank_field = 'HİZMET_KOM ORAN  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 23 bank_field = 'HİZMET_KOM_TUTAR  ' alv_field = 'COMMISSION_AMOUNT' date_format = '' time_format = '' amount_format = '0.00,00' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 24 bank_field = 'IKP ORAN  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 25 bank_field = 'IKP TUTAR  ' alv_field = 'COMMISSION_AMOUNT' date_format = '' time_format = '' amount_format = '0.00,00' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 26 bank_field = 'NET_TUTAR  ' alv_field = 'NET_AMOUNT' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 27 bank_field = 'DOVİZ  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 28 bank_field = 'SİPARİŞ NUMARASI  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 29 bank_field = 'Bloke Süresi  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 30 bank_field = 'Bloke Tipi  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 31 bank_field = 'Bloke Hesap No  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 32 bank_field = 'Taksitli Bloke Hesap No  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 33 bank_field = 'Vadesiz Hesap No  ' alv_field = 'ZZACCOUNT_NUMBER' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 34 bank_field = 'ŞUBE KODU  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 35 bank_field = 'ŞUBE ADI  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 36 bank_field = 'İŞLEM AÇIKLAMA  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 37 bank_field = 'GÜNSONU TARİHİ  ' alv_field = 'ZZEND_OF_DAY_DATE' date_format = 'DD/MM/YYYY' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 38 bank_field = 'BLOKE NO  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 39 bank_field = 'BANKA KODU  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 40 bank_field = 'İŞLEM KODU  ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 6 bank_field_no = 41 bank_field = 'İŞLEM TÜRÜ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 1 bank_field = 'VALOR' alv_field = 'VALUE_DATE' date_format = 'DD.MM.YYYY' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 2 bank_field = 'SUBE' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 3 bank_field = 'HESAPNO' alv_field = 'ZZACCOUNT_NUMBER' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 4 bank_field = 'ISYERINO' alv_field = 'WORKPLACE_NO' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 5 bank_field = 'BRUT_TUTAR' alv_field = 'GROSS_AMOUNT' date_format = '' time_format = '' amount_format = '0.00' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 6 bank_field = 'KOMISYON' alv_field = 'COMMISSION_AMOUNT' date_format = '' time_format = '' amount_format = '0.00' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 7 bank_field = 'NET_TUTAR' alv_field = 'NET_AMOUNT' date_format = '' time_format = '' amount_format = '0.00' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 8 bank_field = 'ISLEMTARIH' alv_field = 'TRANSACTION_DATE' date_format = 'DD.MM.YYYY' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 9 bank_field = 'ISLEM' alv_field = 'PROCESS_TYPE' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 10 bank_field = 'URUN' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 11 bank_field = 'SERVİS KOM.' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 12 bank_field = 'ODUL_KATKISI' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 13 bank_field = 'ANA_MERKEZ_ODUL' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 14 bank_field = 'ANAMRK_SERVİS KOM.' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 15 bank_field = 'FIRMA' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 16 bank_field = 'IBAN' alv_field = 'ZZIBAN' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 17 bank_field = 'ISYERISOSYALKATKI' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 18 bank_field = 'PROGRAMUCRETI' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 19 bank_field = 'ANAMRKSOSYALKATKI' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 20 bank_field = 'ANAMRKPRGRAMUCRET' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 21 bank_field = 'SERVİS ÜCRET TİPİ' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 22 bank_field = 'BATCHN' alv_field = 'PROVISION_APR_CODE' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 23 bank_field = 'TERMİNALN' alv_field = 'TERMINAL_NO' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 24 bank_field = 'KART NUMARASI' alv_field = 'CARD_NO' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 25 bank_field = 'İŞYERİ BİLGİSİ' alv_field = 'ZZMEMBER_WORKPLC_NAME' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 26 bank_field = 'RETREF NO' alv_field = 'ZZCENTER_NUMBER' date_format = '' time_format = '' amount_format = '' )
    ( mandt = sy-mandt bukrs = '1000' bank_no = 7 bank_field_no = 27 bank_field = 'SİPARİŞ NUMARASI' alv_field = '' date_format = '' time_format = '' amount_format = '' )
    ).

    MODIFY yop_t_posfield FROM TABLE @lt_data.
    COMMIT WORK.
  ENDMETHOD.