  METHOD RUN_ALL.
    LOAD_YOP_T_BANKACC(  ).
    LOAD_YOP_T_BANKFORMAT(  ).
    LOAD_YOP_T_BNKINF( ).
    LOAD_YOP_T_FIELDCALC(  ).
    LOAD_YOP_T_POSFIELD(  ).
    LOAD_YOP_T_PTYPEMATCH(  ).
  ENDMETHOD.